# Generated by Django 4.2.2 on 2023-11-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('cajid', models.AutoField(primary_key=True, serialize=False)),
                ('cajanumero', models.IntegerField()),
            ],
            options={
                'db_table': 'caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clid', models.AutoField(primary_key=True, serialize=False)),
                ('clci', models.BigIntegerField(unique=True)),
                ('clpnom', models.CharField()),
                ('clape', models.CharField()),
                ('clfechanacimiento', models.DateField()),
                ('clsexo', models.CharField()),
                ('cltelefono', models.BigIntegerField()),
                ('afiliado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('comid', models.AutoField(primary_key=True, serialize=False)),
                ('fechacom', models.DateTimeField(blank=True, null=True)),
                ('igtf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('devid', models.AutoField(primary_key=True, serialize=False)),
                ('razondev', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('empci', models.BigIntegerField(unique=True)),
                ('empnom', models.CharField()),
                ('empape', models.CharField()),
                ('fechaingreso', models.DateField()),
                ('fechanacimiento', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('puesto', models.CharField()),
                ('empsexo', models.CharField()),
                ('fechasalida', models.DateField(blank=True, null=True)),
                ('bono', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('faltaid', models.AutoField(primary_key=True, serialize=False)),
                ('fechafalta', models.DateField()),
                ('causa', models.CharField()),
            ],
            options={
                'db_table': 'falta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('gasid', models.AutoField(primary_key=True, serialize=False)),
                ('alquiler', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('servicioagua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicioluz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suministrolim', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mantenimientoelec', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastomulta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'gastos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_nombre', models.CharField(max_length=50)),
                ('l_tipo', models.CharField(max_length=50)),
                ('l_cod_postal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lugar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('ofid', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('formapago', models.CharField(blank=True, null=True)),
                ('pago_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidoprooveedor',
            fields=[
                ('pedid', models.AutoField(primary_key=True, serialize=False)),
                ('costobr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igtf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'pedidoprooveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prodcompra',
            fields=[
                ('pcid', models.AutoField(primary_key=True, serialize=False)),
                ('cantcom', models.IntegerField()),
            ],
            options={
                'db_table': 'prodcompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idprod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('presentacion', models.CharField()),
                ('seccion', models.CharField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costoind', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prid', models.AutoField(primary_key=True, serialize=False)),
                ('prrif', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockalmacen',
            fields=[
                ('stalid', models.AutoField(primary_key=True, serialize=False)),
                ('fechavencido', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'stockalmacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocktienda',
            fields=[
                ('sttid', models.AutoField(primary_key=True, serialize=False)),
                ('fechavencido', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'stocktienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucid', models.AutoField(primary_key=True, serialize=False)),
                ('horaapertura', models.TimeField()),
                ('horacierre', models.TimeField(blank=True, null=True)),
                ('extension', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
    ]
